<a href="https://colab.research.google.com/github/ibrahim10sy/learn-python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Tableux numpy***

In [ ]:
import numpy as np

In [ ]:
my_liste = [1, 2, 3, 4, 5]
type(my_liste)


list

In [ ]:
 my_arr = np.array(my_liste)

In [ ]:
type(my_arr)


numpy.ndarray

In [ ]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
print(my_matrix[0][-1])

3


In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 101,20)

array([  0,  20,  40,  60,  80, 100])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.random.rand(2,3)

array([[0.91458769, 0.19240117, 0.73658479],
       [0.03794486, 0.10316716, 0.99490688]])

In [ ]:
np.random.randn(2,3)

array([[ 0.02648647, -0.92156421, -0.33713776],
       [ 1.13570373, -0.51701075,  2.1076334 ]])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
arr = np.arange(0, 25)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr = np.random.randint(0, 101,20)
ranarr

array([ 91,  59,  79,  14,  61,  61,  46,  61,  50,  54,  63,   2, 100,
        50,   6,  20,  72,  38,  17,   3])

In [ ]:
ranarr.max()

100

In [ ]:
ranarr.argmax()

12

# ***Indexation et selection numpy***

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[:-5]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[0:5] = 101
arr

array([101, 101, 101, 101, 101,   5,   6,   7,   8,   9,  10])

In [ ]:
slice = arr[0:5]
slice

array([101, 101, 101, 101, 101])

In [ ]:
slice[:] = 99
slice

array([99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
# Pour copié un tableau

In [ ]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
#Tableau array de deux dimensions
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape #Donne la taille du tableau

(3, 3)

In [ ]:
arr_2d[0][1]

10

In [ ]:
arr1 = np.arange(1, 11) #Création du tableau
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 > 4  #Condition pour vérifier les valeurs supérieur à 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr1 > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr1[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

# ***Opérations numpy***

In [ ]:
op = np.arange(0, 10)
op

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
op + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
op - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
op + op

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#racine carré
np.sqrt(op)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
op.sum()

45

In [ ]:
op.mean()

4.5

In [ ]:
op.min()

0

In [ ]:
op.var()

8.25

In [ ]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d.sum(axis=0) #Somme des colonnes

array([50, 55, 60, 65, 70])

In [ ]:
arr2d.sum(axis=1, keepdims=True) #Somme des lignes

array([[ 10],
       [ 35],
       [ 60],
       [ 85],
       [110]])

In [ ]:
arr2d.sum(axis=1) #Somme des lignes

array([ 10,  35,  60,  85, 110])

# ***Exercice corrigé***

In [ ]:
# Tableau de 1à zeros
arr0 = np.zeros(10)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Tableau de 1à zeros
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#Matrix d'identité 3x3
arr_matrix = np.eye(3)
arr_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Indexation du matrix
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:][0][2]

13

In [ ]:
np.random.rand(1) #generer un nombre aleatoire entre 0 et 1

array([0.1905143])