<a href="https://colab.research.google.com/github/ibrahim10sy/learn-python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Tableux numpy***

In [45]:
import numpy as np

In [ ]:
my_liste = [1, 2, 3, 4, 5]
type(my_liste)


list

In [ ]:
 my_arr = np.array(my_liste)

In [ ]:
type(my_arr)


numpy.ndarray

In [ ]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
print(my_matrix[0][-1])

3


In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 101,20)

array([  0,  20,  40,  60,  80, 100])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.random.rand(2,3)

array([[0.91458769, 0.19240117, 0.73658479],
       [0.03794486, 0.10316716, 0.99490688]])

In [ ]:
np.random.randn(2,3)

array([[ 0.02648647, -0.92156421, -0.33713776],
       [ 1.13570373, -0.51701075,  2.1076334 ]])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
arr = np.arange(0, 25)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr = np.random.randint(0, 101,20)
ranarr

array([ 91,  59,  79,  14,  61,  61,  46,  61,  50,  54,  63,   2, 100,
        50,   6,  20,  72,  38,  17,   3])

In [ ]:
ranarr.max()

100

In [ ]:
ranarr.argmax()

12

# ***Indexation et selection numpy***

In [48]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[8]

8

In [50]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [51]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [52]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [53]:
arr[:-5]

array([0, 1, 2, 3, 4, 5])

In [54]:
arr[0:5] = 101
arr

array([101, 101, 101, 101, 101,   5,   6,   7,   8,   9,  10])

In [55]:
slice = arr[0:5]
slice

array([101, 101, 101, 101, 101])

In [56]:
slice[:] = 99
slice

array([99, 99, 99, 99, 99])

In [57]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [58]:
# Pour copié un tableau

In [59]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])